### ISSUE TITLE
Error with docker run --volumes-from $OVPN_DATA --rm -it martin/openvpn initpki

### ISSUE THREAD

**Issue by LM1LC3N7** [chadoe/docker-openvpn#1]
Hello,

When I run

``` sh
docker run --volumes-from $OVPN_DATA --rm -it martin/openvpn initpki
```

I have this :

``` sh
/usr/local/bin/initpki: line 13: /etc/openvpn/ovpn_env.sh: No such file or directory
```

**Comment by chadoe** [comment]
You need to run the initopenvpn command from step 2 first, that will generate the ovpn_env.sh file needed for the initpki command. It should output "Successfully generated config". Looks like you didn't run that command or are not using the same volume with both commands ($OVPN_DATA variable).
