### ISSUE TITLE
key-direction not set when importing ovpn file

### ISSUE THREAD

**Issue by peterrosell** [chadoe/docker-openvpn#5]
When importing ovpn file in Ubuntu 16.04's Network Manager it fails to set the key-direction. Someone found that if the key-direction is specified above the `<tls-auth>` tag it works.

A fix for the network manager seems to be in place, https://github.com/GNOME/network-manager-openvpn/commit/28636684a268e280accaeb378f00f4a80e9e0377

I will create a PR to fix the ovpn generation so we don't have to wait for that fix.

**Comment by chadoe** [comment]
PR #6 merged
